"""initial schema

Revision ID: 07b95322b0cb
Revises:
Create Date: 2026-09-04 00:46:26.137239
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "07b95322b0cb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "album_target",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("release_group_mbid", sa.String(length=36), nullable=False),
        sa.Column("artist_name", sa.String(length=255), nullable=False),
        sa.Column("artist_mbid", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("primary_type", sa.String(length=32), nullable=True),
        sa.Column("secondary_types", sa.JSON(), nullable=False),
        sa.Column("first_release_year", sa.Integer(), nullable=True),
        sa.Column("preferred_release_mbid", sa.String(length=36), nullable=True),
        sa.Column("library_status", sa.String(length=16), nullable=False),
        sa.Column("library_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("release_group_mbid"),
    )
    op.create_table(
        "budget_ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week", sa.String(length=8), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("grabs", sa.Integer(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week", "source", name="uq_budget_week_source"),
    )
    with op.batch_alter_table("budget_ledger", schema=None) as batch_op:
        batch_op.create_index("ix_budget_week", ["week"], unique=False)

    op.create_table(
        "acquisition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("album_target_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_grab_id", sa.Integer(), nullable=True),
        sa.Column("search_retries", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["album_target_id"],
            ["album_target.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("acquisition", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_acquisition_album_target_id"), ["album_target_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_acquisition_state"), ["state"], unique=False)

    op.create_table(
        "signal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("recording_mbid", sa.String(length=36), nullable=True),
        sa.Column("source_playlist_mbid", sa.String(length=36), nullable=True),
        sa.Column("source_playlist_name", sa.String(length=255), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("requested_artist", sa.String(length=255), nullable=True),
        sa.Column("requested_title", sa.String(length=255), nullable=True),
        sa.Column("requested_mbid", sa.String(length=36), nullable=True),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("album_target_id", sa.Integer(), nullable=True),
        sa.Column("resolution_status", sa.String(length=16), nullable=False),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["album_target_id"],
            ["album_target.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_playlist_mbid", "position", name="uq_signal_playlist_position"),
    )
    with op.batch_alter_table("signal", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_signal_recording_mbid"), ["recording_mbid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_signal_source_playlist_mbid"), ["source_playlist_mbid"], unique=False
        )

    op.create_table(
        "candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("acquisition_id", sa.Integer(), nullable=False),
        sa.Column("prowlarr_guid", sa.String(length=512), nullable=False),
        sa.Column("indexer_id", sa.Integer(), nullable=False),
        sa.Column("indexer_name", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("download_url", sa.String(length=1024), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("seeders", sa.Integer(), nullable=True),
        sa.Column("leechers", sa.Integer(), nullable=True),
        sa.Column("freeleech", sa.Boolean(), nullable=False),
        sa.Column("parsed_quality", sa.JSON(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("rejected_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["acquisition_id"],
            ["acquisition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_acquisition_id"), ["acquisition_id"], unique=False
        )

    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("acquisition_id", sa.Integer(), nullable=True),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["acquisition_id"],
            ["acquisition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_acquisition_id"), ["acquisition_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_event_signal_id"), ["signal_id"], unique=False)

    op.create_table(
        "grab_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("acquisition_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("deluge_instance", sa.String(length=32), nullable=False),
        sa.Column("infohash", sa.String(length=40), nullable=False),
        sa.Column("torrent_name", sa.String(length=512), nullable=True),
        sa.Column("download_location", sa.String(length=1024), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_path", sa.String(length=1024), nullable=True),
        sa.Column("last_progress_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_total_done", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["acquisition_id"],
            ["acquisition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("grab_attempt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_grab_attempt_acquisition_id"), ["acquisition_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_grab_attempt_infohash"), ["infohash"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grab_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grab_attempt_infohash"))
        batch_op.drop_index(batch_op.f("ix_grab_attempt_acquisition_id"))

    op.drop_table("grab_attempt")
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_signal_id"))
        batch_op.drop_index(batch_op.f("ix_event_acquisition_id"))

    op.drop_table("event")
    with op.batch_alter_table("candidate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_acquisition_id"))

    op.drop_table("candidate")
    with op.batch_alter_table("signal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signal_source_playlist_mbid"))
        batch_op.drop_index(batch_op.f("ix_signal_recording_mbid"))

    op.drop_table("signal")
    with op.batch_alter_table("acquisition", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_acquisition_state"))
        batch_op.drop_index(batch_op.f("ix_acquisition_album_target_id"))

    op.drop_table("acquisition")
    with op.batch_alter_table("budget_ledger", schema=None) as batch_op:
        batch_op.drop_index("ix_budget_week")

    op.drop_table("budget_ledger")
    op.drop_table("album_target")
    # ### end Alembic commands ###
