"""m5 album target track lengths

Revision ID: 234ba9a2550b
Revises: 996b5c56335d
Create Date: 2026-09-07 15:33:34.051020
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "234ba9a2550b"
down_revision = "996b5c56335d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("album_target", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("track_lengths", sa.JSON(), nullable=False, server_default="{}")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("album_target", schema=None) as batch_op:
        batch_op.drop_column("track_lengths")

    # ### end Alembic commands ###
