"""m1 nullable target and release mbids

Revision ID: 39409886ba1b
Revises: 07b95322b0cb
Create Date: 2026-09-06 19:54:36.823519
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "39409886ba1b"
down_revision = "07b95322b0cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("acquisition", schema=None) as batch_op:
        batch_op.alter_column("album_target_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("album_target", schema=None) as batch_op:
        batch_op.add_column(sa.Column("release_mbids", sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("album_target", schema=None) as batch_op:
        batch_op.drop_column("release_mbids")

    with op.batch_alter_table("acquisition", schema=None) as batch_op:
        batch_op.alter_column("album_target_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
