"""drop budget ledger

Revision ID: 737b49a1f5b7
Revises: ff7ce52a4c47
Create Date: 2026-09-06 23:12:53.685996
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "737b49a1f5b7"
down_revision = "ff7ce52a4c47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("budget_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_week"))

    op.drop_table("budget_ledger")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_ledger",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("week", sa.VARCHAR(length=8), nullable=False),
        sa.Column("source", sa.VARCHAR(length=64), nullable=False),
        sa.Column("grabs", sa.INTEGER(), nullable=False),
        sa.Column("bytes", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week", "source", name=op.f("uq_budget_week_source")),
    )
    with op.batch_alter_table("budget_ledger", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_budget_week"), ["week"], unique=False)

    # ### end Alembic commands ###
