"""m5 grab attempt download shape

Revision ID: 996b5c56335d
Revises: 7ddeb7f0b04c
Create Date: 2026-09-07 13:36:37.568732
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "996b5c56335d"
down_revision = "7ddeb7f0b04c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grab_attempt", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("download_shape", sa.JSON(), nullable=False, server_default="{}")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grab_attempt", schema=None) as batch_op:
        batch_op.drop_column("download_shape")

    # ### end Alembic commands ###
