"""m4 import job on grab attempt

Revision ID: 9aa229a53b37
Revises: 737b49a1f5b7
Create Date: 2026-09-06 23:23:32.972536
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "9aa229a53b37"
down_revision = "737b49a1f5b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grab_attempt", schema=None) as batch_op:
        batch_op.add_column(sa.Column("import_job_id", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("import_started_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grab_attempt", schema=None) as batch_op:
        batch_op.drop_column("import_started_at")
        batch_op.drop_column("import_job_id")

    # ### end Alembic commands ###
