"""acquisition signal link

Revision ID: d18dc61b90a7
Revises: 9aa229a53b37
Create Date: 2026-09-07 00:16:34.115304
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "d18dc61b90a7"
down_revision = "9aa229a53b37"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("acquisition", schema=None) as batch_op:
        batch_op.add_column(sa.Column("signal_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_acquisition_signal_id_signal", "signal", ["signal_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("acquisition", schema=None) as batch_op:
        batch_op.drop_constraint("fk_acquisition_signal_id_signal", type_="foreignkey")
        batch_op.drop_column("signal_id")

    # ### end Alembic commands ###
