"""m3 grab attempt completed location

Revision ID: ff7ce52a4c47
Revises: 39409886ba1b
Create Date: 2026-09-06 21:59:52.525192
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "ff7ce52a4c47"
down_revision = "39409886ba1b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grab_attempt", schema=None) as batch_op:
        batch_op.add_column(sa.Column("completed_location", sa.String(length=1024), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grab_attempt", schema=None) as batch_op:
        batch_op.drop_column("completed_location")

    # ### end Alembic commands ###
